### ISSUE TITLE
ViewConfiguration not applied

### ISSUE THREAD

**Issue by nouhouari** [TGFTech/angular-cesium#101]
I created a component with a simple map and I'm trying to apply some default settings like in the demo-app example.

I imported the configuration service
`import { ViewerConfiguration } from 'angular-cesium/src/services/viewer-configuration/viewer-configuration.service';
`
```
providers: [
   ...
    ViewerConfiguration
  ]
```
And configure the viewer in the component constructor

```
constructor(public trackService: TrackService, public viewerConf: ViewerConfiguration) {
    viewerConf.viewerOptions = {
      sceneMode: Cesium.SceneMode.COLUMBUS_VIEW,
      selectionIndicator: false,
      timeline: false,
      infoBox: false,
      fullscreenButton: false,
      baseLayerPicker: false,
      animation: false,
      homeButton: false,
      geocoder: false,
      navigationHelpButton: false,
      navigationInstructionsInitiallyVisible: false,
    };
   ...
```
It seems that the configuration is not applied. I can still see the timeline, geocoder,...
I'm using 0.0.18 version.

**Comment by eitanfr** [comment]
1. change to `import { ViewerConfiguration } from 'angular-cesium`
2. in which component did you did `providers: [ViewerConfiguration]` ? was it in the same or above hierarchy of `ac-map`?

**Comment by nouhouari** [comment]
It's working now. Thank you @eitanfr 

I was misled by the code sample.

I changed the import to :
`import { ViewerConfiguration } from 'angular-cesium';`

Add the provider
```
providers: [
   ...
    ViewerConfiguration
  ]
```

And now I can inject the ViewerConfiguration service and change the map settings.

```
constructor(...,public viewerConf: ViewerConfiguration) {

viewerConf.viewerOptions = {
      sceneMode: Cesium.SceneMode.SCENE3D,
      selectionIndicator: false,
      timeline: false,
      infoBox: false,
      fullscreenButton: false,
      baseLayerPicker: false,
      animation: false,
      homeButton: false,
      geocoder: false,
      navigationHelpButton: false,
      navigationInstructionsInitiallyVisible: false,
      terrainProvider: new Cesium.CesiumTerrainProvider({
        url: '//assets.agi.com/stk-terrain/world'
      }),
    };
```
