### ISSUE TITLE
forRoot Error in 0.0.19

### ISSUE THREAD

**Issue by nickyxu** [TGFTech/angular-cesium#107]
hi eitanfr,
    I update my application to version 0.0.19. 
Following the guid to update, I get an error.
" ERROR in Error encountered resolving symbol values statically. Calling function 'AngularCesiumModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in D:/SupreVision//src/app/app.module.ts, resolving symbol AppModule in D:/SupreVision/src/app/app.module.ts"

I am sure this is from AngularCesiumModule.forRoot().
How to fix it?

Thanks.

**Comment by eitanfr** [comment]
we on it, fix will be released soon :)

**Comment by eitanfr** [comment]
fixed #110
