### ISSUE TITLE
About Ac-html

### ISSUE THREAD

**Issue by nickyxu** [TGFTech/angular-cesium#114]
Dear all,
     I study the ac-html component now. I have some question.
1. In my opinion, the html feature either overlay the map with screen position, or embed in the map with world position. However, in our implement the html feature only provide the second one.

2. There is not a ac-html-desc feature. I mean the ac-html feature is very family with ac-label, there should be an observable array to stream.

cheers,
Nicky

**Comment by eitanfr** [comment]
About 1, I think using a normal div with fixed or absolute position is the best solution for screenPosition 
About 2, we are planning to add `ac-html-desc` that will support an observable array.
