### ISSUE TITLE
STYLES not being applied to cesiumContainer that is not in root module/component

### ISSUE THREAD

**Issue by CHBaker** [TGFTech/angular-cesium#115]
I have a "globe" component that I hold my cesium widget in, When I used the specified styles from the tutorial they are not applied. My styles are written in the globe.components.css file, and my html, body width and heights are set. my cesium viewer is 100% in width but not in height, I tried using .map-container (because editing this class in chrome allowed me to set the map at the right height) but the .css file cannot reach the classes within the ac-map attribute

globe.module.ts:
```
import { AngularCesiumModule } from 'angular-cesium';
import { GlobeComponent } from './globe.component';
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';

@NgModule({
  declarations: [
    GlobeComponent
  ],
  imports: [
    AngularCesiumModule.forRoot()
  ]
})

export class GlobeModule {}

```

globe.component.html
```
<ac-map></ac-map>
```

globe.component.css
```
@import url(/node_modules/cesium/Build/Cesium/Widgets/widgets.css);

#cesiumContainer {
    width: 100%;
    height: 720px;
    margin: 0;
    padding: 0;
    overflow: hidden;
}

.map-container {
    width: 100%;
    height: 720px;
    margin: 0;
    padding: 0;
    overflow: hidden;
}
```

globe.component.ts
```
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-globe',
    templateUrl: './globe.component.html',
    styleUrls: [
        './globe.component.css'
    ],
})
export class GlobeComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
```

Sorry if this is not where you guys want inquiries posted, It is unclear in the docs changes that need to be made if you do not host cesium in the root component

**Comment by CHBaker** [comment]
I am trying to integrate cesium into my angular 4 app. I am no using it in the root module, and for the time being all the cesium layer code is written in javascript. can I still integrate with angular-cesium?

**Comment by eitanfr** [comment]
hi ,
*  Using custom styling didnt work for you because of angular encapsulation feature,
if you want that your component style will affect all elements add this to your component metadata: 
```typescript
@Component({
  ...
  encapsulation: ViewEncapsulation.None,
}
```
or if you use angular cli you can set your style in the style.css file .
Also there is an example in the demo with ac-map created not inside the root component. 

* Yes you can do what ever you want with cesium we only provide extra features and upgrade the api. We expose the cesium viewer trough [`MapsManagerService`](https://tgftech.github.io/angular-cesium/injectables/MapsManagerService.html) or [`CesiumService`](https://tgftech.github.io/angular-cesium/injectables/CesiumService.html).

**Comment by CHBaker** [comment]
@eitanfr thanks for the response, I was wondering if that was the reason. I will implement that method.

As for adding in raw javascript to your api to add map overlay etc... how would I do that? is there an example? I'm extremely new to cesium, so I apologize for all the questions.

**Comment by CHBaker** [comment]
@eitanfr where is the demo where cesium is not in the root module? I can't seem to find anything

**Comment by eitanfr** [comment]
Sorry i misguided you, in our demo angular cesium is declared in the root module. But the usage of ac map is in a child component.
The demo is inside the 'demo' directory in our repo
