### ISSUE TITLE
Invalid asm.js

### ISSUE THREAD

**Issue by CHBaker** [TGFTech/angular-cesium#122]
After running basic set up and getting angular-cesium up and running,

warning in the console:
```Invalid asm.js: Invalid member of stdlib        globe:557```

**Comment by eitanfr** [comment]
looks like a chrome issue. 
https://github.com/AnalyticalGraphicsInc/cesium/issues/5847

**Comment by CHBaker** [comment]
thanks! hopefully gets figured out soon.
