### ISSUE TITLE
KML docs? feature request

### ISSUE THREAD

**Issue by CHBaker** [TGFTech/angular-cesium#123]
Hello, Cesium.js has many examples in there docs of different data types, one of the most common being KML. Would you guys consider adding a KML example to the docs?

I have a stack question [here](https://stackoverflow.com/questions/46532013/how-to-stream-kml-into-ac-layer-in-angular-cesium) and would be willing to right up a docs example in a pull request if I can be shown how to do this

**Comment by eitanfr** [comment]
hi, 
Currently, angular-cesium doesn't support KML directly.
We are planning to add a component for loading KML, also PR is welcomed :)
for now as workaround you can use pure cesium API:
```
class YourComponent {
 constructor(private mapsManagerService: MapsManagerService) {
   const viewer = mapsManagerService.getMap().getCesiumViewer()

   viewer.dataSources.add(Cesium.KmlDataSource.load('../../SampleData/kml/bikeRide.kml',options))
 }
}
```

**Comment by CHBaker** [comment]
thanks for the the reply, and the example.
In that case, I'm looking forward to that feature. 

One more request though, as someone new to cesium as well as Angular-Cesium, could you include a section in the docs for accessing basic pure Cesium API components directly like you did above?

I had been struggling to access the viewer directly before you posted this, so it could be helpful to others who are new to Cesium as well and have jumped into Angular-Cesium

**Comment by eitanfr** [comment]
added: 
https://github.com/TGFTech/angular-cesium#mapsmanagerservice

@CHBaker is it clear enough? also PRs to the doc are welcomed :)

**Comment by CHBaker** [comment]
That's really clear, thanks! as I dig more into it I will definitely keep  contributing
