### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by z3214965** [TGFTech/angular-cesium#129]
use ac-box-desc，Create multiple entities，when I update show attribute true->false，An error occurred

![default](https://user-images.githubusercontent.com/18589356/31659693-9337ff68-b367-11e7-8fe3-cf2fa55a6f08.png)

**Comment by z3214965** [comment]
This problem also occurs ac-cylinder-desc、ac-ellipse-desc.........

**Comment by eitanfr** [comment]
Can you please add the code you trying to run

**Comment by z3214965** [comment]
updatePlotObj(obj: any, acLayer: AcLayerComponent) {
    try {
      let currentEntity = acLayer.getStore().get(obj.id);
      if (!currentEntity) {
        alert("没有找到要更新的对象！");
        return;
      }

      switch (obj.name) {
        case "name": {
          this._objectTreeService.object.label = obj.value; 
          currentEntity[obj.name] = obj.value;
          break;
        }
        case "lon": {
          this.positions = [];
          var cartographic = Cesium.Cartographic.fromCartesian(currentEntity["position"]);
          var latitude = Cesium.Math.toDegrees(cartographic.latitude).toFixed(6) * 1.0;
          currentEntity["position"] = Cesium.Cartesian3.fromDegrees(obj.value, latitude);
          break;
        }
        case "lat": {
          this.positions = [];
          var cartographic = Cesium.Cartographic.fromCartesian(currentEntity["position"]);
          var longitude = Cesium.Math.toDegrees(cartographic.longitude).toFixed(6) * 1.0;
          currentEntity["position"] = Cesium.Cartesian3.fromDegrees(longitude, obj.value);
          break;
        }
        case "pheight": {
          // this.positions = [];
          // currentEntity["position"] = Cesium.Cartesian3.fromDegrees(this.positions[0], this.positions[1], obj.value);
          break;
        }
        case "x":
        case "y":
        case "z": {
          if (currentEntity.objectType === SVObjectType.boxGraphics) {
            currentEntity["dimensions"][obj.name] = obj.value;
          }
          if (currentEntity.objectType === SVObjectType.ellipsoidGraphics) {
            currentEntity["radii"][obj.name] = obj.value;
          }
          break;
        }
        case "font": {
          currentEntity[obj.name] = obj.fontSize;
          break;
        }
        case "bimageName": {
          currentEntity["bimageName"] = obj.value;
          currentEntity["bimage"] = obj.remark;
          break;
        }
        case "imageName": {
          currentEntity["imageName"] = obj.value;
          currentEntity["image"] = obj.remark;
          break;
        }
        case "fillColor":
        case "color":
        case "material": {
          currentEntity[obj.name] = obj.colorValue;
          break;
        }
        default: {
          currentEntity[obj.name] = obj.value;
        }
      }
      acLayer.update(currentEntity, currentEntity.id);
    } catch (error) {
      alert(error);
    }
  }

**Comment by eitanfr** [comment]
do you use <ac-layer> with [store]="true" ?
is currentEntity is a valid entity?

**Comment by z3214965** [comment]
I do not know how get AcLayerComponent entity, so I set up [store]="true"，I update all attributes No problem 	except show attribute
