### ISSUE TITLE
MapEventsManagerService now only initializes after ac-map OnInit causing exceptions on registering to events

### ISSUE THREAD

**Issue by Nirco96** [TGFTech/angular-cesium#131]
After updating to the latest version, I started getting exceptions saying that MapEventsManagerService has not been initialized yet, it needs to be called under <ac-map>. My component registers to the event using the service in it's constructor, and it is inside <ac-map>. This only happened when I updated to 0.0.29, and did not happen before. Thank you.

**Comment by eitanfr** [comment]
hi,
I guess registering to events in ngOnInit is a workaround.
fixed in #133

**Comment by eitanfr** [comment]
check out 0.0.30 :)
