### ISSUE TITLE
Using geoserver as a map provider

### ISSUE THREAD

**Issue by nadavpld** [TGFTech/angular-cesium#168]
Hi,
I am having some hard time configuring angular-cesium to work with a geoserver map provider.
I have tried following the samples here : [samples](https://github.com/TGFTech/angular-cesium/blob/master/demo/app/components/maps-layer/maps-layer.component.html)
But had no success. 
We are migrating from an Angular 1.5 project using CesiumJS with a geoserver map provider.
In CesiumJS we used the Cesium.WebMapServiceImageryProvider , initializing it with a url and a layers property as follows : 
`var imageryProvider = new Cesium.WebMapServiceImageryProvider({
url: url,
layers: layer
})`
Assuming the url to the geoserver is : http://localhost:8080/geoserver/wms
and the layer name is : TrueMarble
What should I do in order to get a map showing ? 
I have tried all variations of
`<ac-map-layer-provider [provider]="MapLayerProviderOptions.WebMapService" [options]="{
url: 'http://localhost:8080/geoserver/wms',
layers: 'TrueMarble' (with or without it)
}"`></ac-map-layer-provider>

I would really appreciate a sample or a guidance.
Thanks,
תודה רבה

**Comment by eitanfr** [comment]
hi,
try running this example , it worked fine for me. (you should see blue dots around austrlia)
```html
<ac-map-layer-provider [provider]="MapLayerProviderOptions.WebMapService"
                       [options]="{
                                  url : 'https://nationalmap.gov.au/proxy/http://geoserver.nationalmap.nicta.com.au/geotopo_250k/ows',
                                layers : 'Hydrography:bores',
                                parameters : {
                                    transparent : true,
                                    format : 'image/png'
                                }
                            }">
</ac-map-layer-provider>
```
maybe the problem is with your geoserver?

**Comment by nadavpld** [comment]
Example works as expected.
But it seems to be using the bing map and just a blank layer with dots on top of it.. Im trying to serve an entire map tiles and replace the bing map.
Geoserver works fine with our old application so he is probably not the issue,
I will try to dig a bit deeper.

**Comment by nadavpld** [comment]
I forgot to mention it, it happens only when working offline (and therefore using the geoserver, otherwise I use the bing map).
When loading the map offline im receiving this error : 
`An error occurred while accessing https://dev.virtualearth.net/REST/v1/Imagery/Metadata/Aerial?incl=ImageryProviders&key=Aig5SkZ4pNMN8b4rX-RUH2c_95mK-wjb4WL9k50K51faErEGnNsxgpWHXiqS3Rhe.`

Could it be that after trying to load the default bing map its not trying to show any other tiles ?
Is there any way I can disable the auto loading of the bing map ?
The browser do load the tiles from the geoserver but they are not shown, I know this for sure because when disconnecting from the local net and connecting to the regular net I get errors that the geoserver is not reachable, errors which I dont get when working offline.

**Comment by eitanfr** [comment]
check out this [issue](https://groups.google.com/forum/#!topic/cesium-dev/bCu1rVIcuUk) .  
seems you are right, you need to configure your imagery provider on cesium viewer bootstrap. 
you can do it with `ViewerConfiguration` service, this service allows you to pass the initial options to the cesium viewer , there you will need to set your imageryProvider, check out this [example](https://github.com/TGFTech/angular-cesium/blob/master/demo/app/components/demo-map/demo-map.component.ts) for ViewerConfiguration usage.

**Comment by nadavpld** [comment]
Thanks, nice catch.
Ended up configuring the imageryProvider like we did in the previous project as you suggested : 
`      imageryProvider: new Cesium.WebMapServiceImageryProvider({
        url: 'http://localhost:8080/geoserver/wms',
        layers: 'nyc:TrueMarble'
      }),` 
Maps shows up with the TrueMarble tiles, works as expected.
The usage of both angular-cesium and "native" cesium might be a bit confusing.
