### ISSUE TITLE
Module AngularCesiumModule can't be used

### ISSUE THREAD

**Issue by danigrosu** [TGFTech/angular-cesium#171]
**Intended outcome:**

**Actual outcome:**
This was tested on Chrome v62.0.3202.94, 64bit.  
I am not able to use the module as described below.

**How to reproduce the issue:**
Just installed cesium and angular-cesium, imported `AngularCesiumModule` etc. as stated in README.md. When I hit `ng serve` I get the following error in console: `SyntaxError {__zone_symbol__error: Error: Can't resolve all parameters for KeyboardControlService: ([object Object], [object Object], ?…, …}`. If I comment AngularCesiumModule from app.module.ts imports the error disappears, but I can't use the module anymore, obviously.

**Version**
- angular-cesium@0.0.35

**Comment by eitanfr** [comment]
can you please add a screenshot with your all your packages versions(package.json file)?

**Comment by danigrosu** [comment]
this is the `package.json` file:  
```
{
  "name": "ac",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "angular-cesium": "0.0.35",
    "cesium": "^1.39.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.1",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "~2.0.0"
  }
}
```

**Comment by eitanfr** [comment]
can you please try to upgrade to angular-cli to 1.2.0~  and angular packages to 4.0.0^

**Comment by danigrosu** [comment]
1. I upgraded the angular-cli, both global and project packages to v1.5.3, and the angular packages to v5.0.0 and it gave me this error: `Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'`  
2. I downgraded the angular packages to v4.3.4 and it worked. Thank you for your support!

**Comment by eitanfr** [comment]
great,
we are working on version for angular 5. you can follow here   #127
