### ISSUE TITLE
Can not set height of Cesium component [Angular5]

### ISSUE THREAD

**Issue by schitzN** [TGFTech/angular-cesium#175]
So i found a workaround for the 'ngOutletContext' exception i get, because i'm working with angular 5 - renaming 'ngOutletContext' to 'ngTemplateOutletContext' because 'ngOutletContext' got removed in angular 5. I do not know if following issue relates to the circumstance that i'm working with angular 5 but i thought it could be important to mention that here! :-)

I than integrated the ac-map into a componant of a sub-module - e.g. not into the root module as the README suggests. I do not get any exceptions and a already see the cesium-component rendered in my browser, but its height is 18px and unfortunately i was not able to fix this.

Any suggestions? Is this due to the fact, that angular-cesium is not optimized for angular5 yet or did i miss something?

**Actual outcome:**

![cesium-component](https://user-images.githubusercontent.com/2317455/33274150-8d01c6cc-d38f-11e7-92aa-4ebe498a8224.JPG)

The ac-map is only 18px high. Stylings (e.g. setting a height) in the corresponding component.scss only apply to the ac-map but does not resize .cesium-viewer. Stylings that would apply to .cesium-viewer are not applied.

There is also a SO question about the same issue, but his workaround of setting the .map-container does not work for me, because the style does not get applied! (https://stackoverflow.com/questions/46409894/how-to-use-angular-cesium-not-in-the-root-module)

**Version**
- angular-cesium@0.035
- cesium@1.39.0
- angular@5

**Comment by eitanfr** [comment]
Hi, related to #127 we are working on a few upgrades and updating to angular 5.
About your map size, could be it related to angular view encapsulation? Do you define your scss in an component? If so use `viewencapsulation.None`
Check out this [issue](https://github.com/TGFTech/angular-cesium/issues/115)

**Comment by schitzN** [comment]
@eitanfr thanks, that worked! I'm fairly new to angular, sry for the inconvenience!

Any idea, when angular5 support will be released?

**Comment by eitanfr** [comment]
we will try to push it until the beginning of the next week , 
also PR are always welcomed :)
