### ISSUE TITLE
ac-layer inside *ngFor

### ISSUE THREAD

**Issue by nadavpld** [TGFTech/angular-cesium#180]
Hi,
I have an unkown number of objects, each of them have uknown number of visited locations I wanted to present.
I followed the examples provided and everything worked fine for one object.
When trying to move to unkown number of users while maintaining the separation, e.g. - not showing all points together, each user has an ac-layer of its own - this way I can manipulate them easily (show\hide etc..).
I have tried the following : 
`<ac-layer *ngFor="let member$ of members$$ | async | mapValues" acFor="let location of members$" [context]="this" [store]="true">`
`                <ac-point-desc props="{
                    pixelSize: 20,
                    position: location.position,
                    color: location.color
                    }">
                </ac-point-desc>`
`            </ac-layer>`

But got 

> ERROR Error: ac-layer: must initailize [acFor] with rx observable, instead received: undefined

members$$ - array of observables
member$ - an observable of locations

After an hour or so I figured its the context that causes the problem and therefore the member$ is undefined - it looks for a member$ in my component.

Can I define the context to something else ? 
Is there any other way to do the above ? assuming that I dont want the simple one ac-layer for all locations solution..

Thanks,
Nadav

**Comment by eitanfr** [comment]
hi, 
maybe [`ac-array-desc`](https://tgftech.github.io/angular-cesium/components/AcArrayDescComponent.html) can help you?
 also there is a usage example in the demo...

**Comment by nadavpld** [comment]
Thanks, it seems to be the solution I was looking for but unfortunately I'm getting : 
> 'ac-array-desc' is not a known element:

It really does not showing under node_modules/angular-cesium/src/angular-cesium/components directory.

**Comment by nadavpld** [comment]
Thanks, this is exactly what I was looking for.
Worked great.
