### ISSUE TITLE
'Error: No provider for MapLayersService!' on using 'ac-layer'

### ISSUE THREAD

**Issue by ghost** [TGFTech/angular-cesium#183]
I am trying to implement the polygon drawer from the demo app by importing the various components into my code. I am using the `angular-cesium` node module, and have copied the missing components from the demo source into my app (`PolygonsEditorLayerComponent` and `PolygonsEditorLayerComponent`, with a little fiddling). However, whenever I use an `ac-layer` component in my app (from `polygons-editor.component.html`), I get the error:
> Error: No provider for MapLayersService!

...even though I am not referencing this service anywhere in my code, thus I believe it is the `angular-cesium` code itself that is trying to inject this service and failing.

I am probably just misunderstanding how to import the library properly, but I believe I have done all I need. In my `AppModule`:

```
@NgModule({
  declarations: [
    AppComponent,
    MapComponent,
    RightOptionsComponent,
    PolygonsEditorLayerComponent,
    PolygonsEditorComponent
  ],
  imports: [
    BrowserModule,
    CoreModule,
    SharedModule,
    AngularCesiumModule.forRoot()
  ],
  bootstrap: [AppComponent],
  providers: []
})
export class AppModule { }
```

What is going on?

**Intended outcome:**
Map displays without error

**Actual outcome:**
No compilation errors, but in the browser:
> Error: No provider for MapLayersService!

**How to reproduce the issue:**
Copy the `PolygonsEditorComponent` from the demo app and insert it into my own app. It seems just using `ac-layer` causes the issue.

**Version**
- angular-cesium@0.0.38

**Comment by marknorgate-tengroup** [comment]
## Update
Having had a fiddle around and commenting out all of the `ac-layer` components, I now receive a new error:
> PolygonsEditorLayerComponent.html:1 ERROR Error: No provider for CesiumEventBuilder!

This occurs trying to inject a `MapEventsManagerService` into my `PolygonsEditorComponent`. I'm clearly doing something very wrong! Any ideas?

**Comment by eitanfr** [comment]
hi,
first, you should declare `PolygonsEditorComponent`.  then: 
* add `AngularCesiumWidgetsModule` to your app.moudle 
* put `<polygons-editor>` some where under `ac-map` as shown [here](https://github.com/TGFTech/angular-cesium/blob/master/demo/app/components/editor-layer/polygons-editor-layer/polygons-editor-layer.component.html)
* provide `PolygonsEditorService` as shown (here)[https://github.com/TGFTech/angular-cesium/blob/master/demo/app/components/editor-layer/polygons-editor-layer/polygons-editor-layer.component.ts]   
I guess we need to improve the doc for the editors...

**Comment by danigrosu** [comment]
Hi. Almost same error here:  
![err](https://user-images.githubusercontent.com/17656677/33661776-105067c8-da92-11e7-9434-8a424b15f4d1.PNG)

I am trying to manage the clicks on the map so I followed the steps from tutorial, i.e. 
```
@Component(...)
export class SomeComponent{
  constructor(private eventManager: MapEventsManagerService){
    
    // Input about the wanted event 
    const eventRegistration: EventRegistrationInput = {
      event: CesiumEvent.LEFT_CLICK, // event type enum. [required!]
      modifier: CesiumEventModifier.CTRL, // event modifier enum. [optional]
      entityType: AcEntity, // raise event only if AcEntity is clicked. [optional] 
      priority: 0, // event priority, default 0 . [optional]
      pick: PickOptions.PICK_FIRST // entity pick option, default PickOptions.NO_PICK. [optional]
    };
    const clickEvent = this.eventManager.register(eventRegistration).subscribe((result) => {
          // The EventResult will contain: 
          // movement(screen location of the event), entities(your entities) , primitives( cesium primitives, like label,billboard...)
    	  console.log('map click', result.movement, 'primitives:', result.primitives, 'entities', result.entities);
    	});
  } 
}
```
From my point of view I added the corresponding services to the NgModule providers array, but clearly something is wrong.

```
@NgModule({
  declarations: [
    AppComponent,
  ],
  entryComponents: [
  ],
  imports: [
    BrowserModule,
    FormsModule,
    AngularCesiumModule.forRoot(),
    AngularCesiumWidgetsModule 
  ],
  providers: [
    HttpService,
    CesiumService,
    MapEventsManagerService,
    CesiumEventBuilder,
    MapLayersService
  ],
  bootstrap: [AppComponent]
})
```

**Comment by nadavpld** [comment]
Same error as @danigrosu 
Trying to handle click events, getting 
`No provider for CesiumService`
After importing it and adding the service as a provider I'm getting
`No provider for CesiumEventBuilder`

Component meta data : 
```
@Component({
  selector: 'app-map',
  templateUrl: './map.component.html',
  providers : [ViewerConfiguration, MapEventsManagerService, CesiumService],
  styleUrls: ['./map.component.css']
})
```
Click event registration and handle in the constructor:
```
const eventRegistration: EventRegistrationInput = {
    event: CesiumEvent.LEFT_CLICK,
    entityType: AcEntity,
    pick: PickOptions.PICK_FIRST
 };

 this.eventManager.register(eventRegistration).subscribe(this.handleMemberClick);

```

**Comment by eitanfr** [comment]
@danigrosu checkout  the answer I wrote for #185
