### ISSUE TITLE
No provider for MapEventsManagerService

### ISSUE THREAD

**Issue by danigrosu** [TGFTech/angular-cesium#185]
**Intended outcome:**
I am trying to handle the left click on the `ac-map`.

**Actual outcome:**
Firstly I tried to inject the `MapEventsManagerService` in the constructor of my component but I got `No provider for MapEventsManagerService` error in console.
```
//ts file
@Component(...)
private provider = Cesium.ArcGisMapServerImageryProvider;
export class SomeComponent{
  constructor(private eventManager: MapEventsManagerService){
    const eventRegistration: EventRegistrationInput = {
      event: CesiumEvent.LEFT_CLICK, // event type enum. [required!]
      modifier: CesiumEventModifier.CTRL, // event modifier enum. [optional]
      entityType: AcEntity, // raise event only if AcEntity is clicked. [optional] 
      priority: 0, // event priority, default 0 . [optional]
      pick: PickOptions.PICK_FIRST // entity pick option, default PickOptions.NO_PICK. [optional]
    };
    const clickEvent = this.eventManager.register(eventRegistration).subscribe((result) => {
    	  console.log('map click', result.movement, 'primitives:', result.primitives, 'entities', result.entities);
    	});
  } 
}
```
I even changed the `entityType: AcEntity` to `entityType: AcMapComponent` because I thought it'd make a difference.
```
//html
<ac-map></ac-map>
```

Secondly I tried to take a reference to the `ac-map` component with `@ViewChild`, i.e.
```
@ViewChild(AcMapComponent) acmap: AcMapComponent;
...
ngOnInit() { // I used the ngOnInit to register the event because the property acmap is set after the constructor calls
    var eventManager = this.acmap.getMapEventsManager();
    ...
    // same code as above
}
```
In this case the error `No provider for MapEventsManagerService` doesn't show up, but nothing happens when clicking the map.

**How to reproduce the issue:**
In order to reproduce this issue, it is enough to create a template file which consists of a `ac-map` component, then create and subscribe to the map click event as stated in the readme. I also tried to include a `ac-map-layer-provider` like this:
```
<ac-map>
    <ac-map-layer-provider  *ngIf="true"
                            [provider]="provider"
                            [options]="{
                                url : 'https://server.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer'
                            }">
    </ac-map-layer-provider>
</ac-map>
```

**Version**
- angular-cesium@0.0.38

**Comment by nadavpld** [comment]
Same error as @danigrosu 
Trying to handle click events, getting 
`No provider for CesiumService`
After importing it and adding the service as a provider I'm getting
`No provider for CesiumEventBuilder`

Component meta data : 
```
@Component({
  selector: 'app-map',
  templateUrl: './map.component.html',
  providers : [ViewerConfiguration, MapEventsManagerService, CesiumService],
  styleUrls: ['./map.component.css']
})
```
Click event registration and handle in the constructor:
```
const eventRegistration: EventRegistrationInput = {
    event: CesiumEvent.LEFT_CLICK,
    entityType: AcEntity,
    pick: PickOptions.PICK_FIRST
 };

 this.eventManager.register(eventRegistration).subscribe(this.handleMemberClick);

```

**Comment by eitanfr** [comment]
hi guys, 
all services are provided by `ac-map` therefor only available under `ac-map` component hierarchy.
but if you want to use those services not under `ac-map` you can use  `MapsManagerService` as explained [here](https://github.com/TGFTech/angular-cesium#mapsmanagerservice).
please tell if it solved your problems .

**Comment by danigrosu** [comment]
WIth `<ac-map></ac-map>` in the template and [this](https://github.com/TGFTech/angular-cesium#map-events) code for constructor, it doesn't work. It gave me the same error.

**Comment by eitanfr** [comment]
hi, 
I will try to explain better, `ac-map` is the provider for all the util services like  `MapEventsManagerService `.
it uses angular dependency injection so `ac-map` component will look something like that:
```typescript
@Component({
  selector: 'ac-map',
  providers: [MapEventsManagerService, ...]
})
class AcMapComponent {}
```
Therefor in order to have access to a service that is provided by a child component you have 2 ways:
* Create child component and ask for it in the constructor , [example](https://github.com/TGFTech/angular-cesium/blob/master/demo/app/components/event-test-layer/event-test-layer.component.ts)
* Use angular `@ChildView()` decorator:
```typescript
// in your component
@ChildView(AcMapComponent) acMap;

ngAfterViewInit() {
  this.acMap.getMapEventsManager();
}
```

* Another way is to use our `MapsManagerService` as shown [here](https://github.com/TGFTech/angular-cesium#mapsmanagerservice). this service allows you to reach your map components any where in your code. 

`MapEventsManagerService` and other util services must be provided by `ac-map` because it is per map instance.

**Comment by danigrosu** [comment]
I have managed to handle the click event using the `ViewChild` approach. The problem was related to the `EventRegistrationInput` object: that options prevented the click event to fire up. I guess I'm closing this...
