### ISSUE TITLE
zIndex on entities level and not only on layer level

### ISSUE THREAD

**Issue by IOZD** [TGFTech/angular-cesium#192]
**Intended outcome:**
I tried to set a z-Index on specific entity but there is no functionality for that 

**Actual outcome:**

I can't set zIndex on entities.

**How to reproduce the issue:**

**Version**
- angular-cesium@0.0.39

**Comment by tomermoshe** [comment]
z-index support is very lacking in cesium.  zindex input in ac-layer works on all graphic entities except billboards, labels polylines and points. 
However zindex is not taken into account if the graphic entity has a height property of some sort (perPositionHeight \ height \ extrudedHeight). If such a property exist, it will override the zIndex of the layer and will be used instead (useful for setting zIndex between entities inside the same layer). 
For setting z index for billboards and labels use eyeOffset with a Cartesian3 that has a negative Z value - (the lower the Z value the higher the z index).
For polylines and points - were looking into it.
