### ISSUE TITLE
Polyine point dragging affects RnB Point Dragging

### ISSUE THREAD

**Issue by IOZD** [TGFTech/angular-cesium#195]
**Intended outcome:**

activate RnB, activate Polyline in edit mode, when I edit the polyline location it should not affect anything but the polyline

**Actual outcome:**

after activating RnB, and Then Polyline Editor, when I change a Polyline Point position it affects the Rnb, and When I stop the editing it leaves a point without anything on the map.

**How to reproduce the issue:**
Create Rnb (int edit mode), create Polyline , try to catch and drag the polyline point -> then you see the RnB moving

**Version**
- angular-cesium@0.0.42

**Comment by tomermoshe** [comment]
will be fixed in 0.0.43
