### ISSUE TITLE
performance issues because of the editor component

### ISSUE THREAD

**Issue by IOZD** [TGFTech/angular-cesium#197]
**Intended outcome:**
regular work and flow of the components

**Actual outcome:**
slow working of the map, editors components create Verbose Warnings that are a symptoms of the problem of the editor components.

**How to reproduce the issue:**

create angular cesium nap with more than one editor component

**Version**
- angular-cesium@0.042

**Comment by tomermoshe** [comment]
will be fixed in 0.0.43
