### ISSUE TITLE
changing the hippodrome points position in editor mode look like a lag

### ISSUE THREAD

**Issue by IOZD** [TGFTech/angular-cesium#198]
**Intended outcome:**

changing the hippodrome  point position made with no problem and the whole hippodrome moves regularly including the width points.

**Actual outcome:**
when changing the hippodrome point position it takes time to change the whole hippodrome positioning and the width points doesn't change their location until the mouseUp event

**How to reproduce the issue:**

open the hippodrome editor, change the points position, and see the behavior described

**Version**
- angular-cesium@0.0.42

**Comment by tomermoshe** [comment]
will be fixed in 0.0.43
