### ISSUE TITLE
rnb - dragging rnb doesn't affect the label until mouse up

### ISSUE THREAD

**Issue by IOZD** [TGFTech/angular-cesium#200]
**Intended outcome:**

when dragging RnB it is expected to drag the whole component including the label (when in editor mode)

**Actual outcome:**

when dragging RnB only the polyline dragged and the label changes position on mouseUp.

**How to reproduce the issue:**

create a RNB, erase the disable in the filter, allow only two points, drag the RnB.

**Version**
- angular-cesium@0.0.42

**Comment by tomermoshe** [comment]
will be fixed in version 0.0.43
