### ISSUE TITLE
add update circle doesn't change the radius of the circle.

### ISSUE THREAD

**Issue by IOZD** [TGFTech/angular-cesium#204]
**Intended outcome:**

when changing the radius of a circle it should change and stay that way.

**Actual outcome:**

after changing the radius of circle it returns to it's initial size.

**How to reproduce the issue:**

create a circle with radius 20,000 (ADD_UPDATE =0 ) --> circle created correctly
change the circle radius to 100,000 (ADD_UPDATE  = 0) --> radius did not update
remark: we do not have this problem in other entities (hippodrome, polygon, point etc..)

**Version**
- angular-cesium@0.0.39^

**Comment by tomermoshe** [comment]
fixed in newer version
