### ISSUE TITLE
terrain data not loaded using WebMapServiceImageryProvider

### ISSUE THREAD

**Issue by danigrosu** [TGFTech/angular-cesium#207]
**Intended outcome:**
I used a GeoserverTerrainPlugin to create terrain data and then I tried to load them in anugular-cesium project!
I inculded the plugin in the angular-cli.json scrips section and below is my code for adding the layer on the globe: 

```
<ac-map-layer-provider [provider]="MapLayerProviderOptions.WebMapServiceImageryProvide 
    [options]="{
        url : 'http://my_gis_server/geoserver/workspace_elevation/wms',
        layers: 'my_layer'
    }">
</ac-map-layer-provider>
```

**Actual outcome:**
there are no errors but the layer is not added on the globe. Do you have any suggestions regarding the provider or any ideas about using external plugins with angular-cesium? 

**How to reproduce the issue:**
I have invoked the `Cesium.GeoserverTerrainProvider()` in the ts file but I don't find any support on how to add it to the `ac-map-layer-provider`.

**Version**
- angular-cesium@0.0.38

**Comment by tomermoshe** [comment]
Please try loading your terrain using the scene's: viewer:`this.cesiumService.getViewer().terrainProvider = new Cesium.CesiumTerrainProvider(
      environment.terrain
    );`

**Comment by eitanfr** [comment]
Closing because of in activity, if the problem continues please open a new issue
