### ISSUE TITLE
polyline dash does not work

### ISSUE THREAD

**Issue by IOZD** [TGFTech/angular-cesium#208]
@tomermoshe 

**Intended outcome:**
create a dashed Polyline 

**Actual outcome:**
the polyline doesn't get the material dash without using  polylineEditor.create(--material data here--)

**How to reproduce the issue:**

the html:

 <ac-layer acFor="let polyLine of polylines$" [context]="this" [zIndex]="1">
    <ac-polyline-desc props="{
      width : polyLine.width,
      positions:polyLine.positionPolyline,
      material: myMaterial,
      show: polyLine.polylineVisible,
      height:polyLine.clientZindex
          
  }">
    </ac-polyline-desc>
  </ac-layer>

the ts:

ngOnInit() {
    this.myMaterial = ()=> Cesium.Material.fromType('PolylineDash', {
      color: Cesium.Color.RED,
      gapColor: Cesium.Color.TRANSPARENT,
      dashLength: 12.0
    });
  }

**Version**
- angular-cesium@0.0.47

**Comment by Georift** [comment]
Dashed polylines are working fine for me, your issue is how you are instantiating **this.myMaterial**. Your syntax of **() =>** is creating a function pointer, remove that and it should work perfectly.

`  private dashedMaterial: any = Cesium.Material.fromType('PolylineDash', {
    color: Cesium.Color.RED,
    gapColor: Cesium.Color.TRANSPARENT,
    dashLength: 12.0
  })`

**Comment by IOZD** [comment]
@Georift thanks, but I've tried this, still won't work for me.
I followed the instruction of 
@eitanfr  in other issue comment from aug 23 , 2017
#88

**Comment by Georift** [comment]
Are you able to render solid polylines with a single colour? eg. this.myMaterial = Cesium.Color.RED

**Comment by tomermoshe** [comment]
I believe you mixed up the old primitives API (which the `ac-polyline-primitive-desc` uses) uses and the entity API (which `ac-polyline-desc` uses). 
Use this instead:
`this.myMaterail = new Cesium.PolylineDashMaterialProperty({
    color : Cesium.Color.BLUE,
    gapColor: Cesium.Color.YELLOW
  });`

**Comment by tomermoshe** [comment]
I tested your material and it works. You just need to change `ac-polyline-desc` to `ac-polyline-primitive-desc` and change `this.myMaterial` to be an object and not a function.

**Comment by IOZD** [comment]
@Georift  yes, but it wasn't the problem(thank you).
@tomermoshe  this what worked for me!
