### ISSUE TITLE
ac-html element is shown when show set to false

### ISSUE THREAD

**Issue by nadavpld** [TGFTech/angular-cesium#216]
**Intended outcome:**
Show a sample div in a specific location over the map

**Actual outcome:**
When show set to true, div is shown correctly

```
<div id="map">
    <ac-map [sceneMode]="sceneMode" id="main-map">
       <ac-html [props]="{position: getMetaDataPosition(), show: true}">;
            <div style="color:white; font-size: 50px;">TEST</div>
        </ac-html>
    </ac-map>
</div>
```
[https://imgur.com/a/O1seE](url)

When show set to false, div is shown on the bottom left side of the page. Seems like the css display property doesnt change.

```
<div id="map">
    <ac-map [sceneMode]="sceneMode" id="main-map">
       <ac-html [props]="{position: getMetaDataPosition(), show: false}">;
            <div style="color:white; font-size: 50px;">TEST</div>
        </ac-html>
    </ac-map>
</div>
```
[https://imgur.com/a/GDNNq](url)

Sorry for the partial screen shots.. couldnt post the original...

**Version**
- angular-cesium@0.0.48

**Comment by popoleeMaster** [comment]
I still have this in the latest 0.6 maybe slightly different

`
<ac-layer #menuLayer acFor="let menu of menu$" [context]="this">
  <ac-html-desc props="{
    position: menu.position,
    fillColor : labelParam.fillColor,
    show: false,
    horizontalOrigin : labelParam.horizontalOrigin,
    verticalOrigin : labelParam.verticalOrigin,
    scale: 0.1,
    pixelOffset : labelParam.pixelOffset,
  }">
    <ng-template let-html>
      My Div show is : {{ html.show }}
        
    </ng-template>
  </ac-html-desc>
</ac-layer>`

https://prnt.sc/pem22r
