### ISSUE TITLE
window['CESIUM_BASE_URL'] = '/assets/cesium' not working in Angular 5

### ISSUE THREAD

**Issue by tdmitchal** [TGFTech/angular-cesium#222]
I have tried to add window['CESIUM_BASE_URL'] = '/assets/cesium'; to the main.ts file in Angular. No matter what CESIUM still tries to pull the images and json files from different location giving me tons of 404.

I was able to fix by initializing Cesium.buildModuleUrl.setBaseUrl('/assets/cesium/');  But this means I can't use the directives <AC-MAP>.

**Comment by tomermoshe** [comment]
Thanks a lot for opening the issue! I will update the readme to address it.
What do you mean by "can't use the directives"? What error are you getting? I just tried to open a demo project with angular cesium and cesium 1.44 and added ```Cesium.buildModuleUrl.setBaseUrl('/assets/cesium/');```
to main.ts and everything seems to be working fine.
