### ISSUE TITLE
StaticInjectorError on testing component that uses ac-layer

### ISSUE THREAD

**Issue by osadan** [TGFTech/angular-cesium#223]
**Intended outcome:**

I am trying to test a component that I used acLayerComponent as ViewChild
```javascript
@ViewChild('acLayer') acLayer: AcLayerComponent
```
```html
<ac-layer #acLayer ac-for...></ac-layer>
```
```javascript
// test 
TestBed.configureTestingModule({
imports: [AngularCesiumModule.forRoot({})],
providers: [
CesiumService,
MapLayersService
]
})
```

**Actual outcome:**

I received an StaticInjectorError[MapLayersService]
I tried to add the MapLayersService in the TestBed.configureTestingModule
but still received the error 
tried to add the service to other module (as providers) still received the error
tried to add the service in the component as internal component provide - still received the error
looked every where in your code but could not find out where you are assigning the service to a module or a component. 

the CesiumService does go through 

**Version**
- angular-cesium@0.0.39

**Comment by eitanfr** [comment]
hi,
MapLayersService is defined by the `ac-map` component. 
Also MapLayersService depends on `CesiumService` which itself depends on other services. 
All the services are provided by `ac-map`, maybe you can add the other services.
Never encountered this error myself, update us if you find a solution.
example for a test:  [here](https://github.com/TGFTech/angular-cesium/blob/master/src/angular-cesium/components/ac-layer/ac-layer.component.spec.ts)

**Comment by osadan** [comment]
I was able to add provider to CesiumService. 
I resolved the problem by mocking the <ac-layer> and all the other components.
I saw the MapLayersService in the di container of angular . but the TestBed.....module could not find it in the StaticInjector
