### ISSUE TITLE
TypeError: Cannot read property '_metadataResolver' of undefined

### ISSUE THREAD

**Issue by nickyxu** [TGFTech/angular-cesium#224]
Dear all,
   I using ac in my app.
It works well in development mode.
However, I get nothing after running 'ng build --prod'.
The error is:
ERROR TypeError: Cannot read property '_metadataResolver' of undefined
    at new e (main.45f8669ff7faba79f093.js:1)
    at main.45f8669ff7faba79f093.js:1
    at To (main.45f8669ff7faba79f093.js:1)
    at xo (main.45f8669ff7faba79f093.js:1)
    at main.45f8669ff7faba79f093.js:1
    at To (main.45f8669ff7faba79f093.js:1)
    at xo (main.45f8669ff7faba79f093.js:1)
    at e.get (main.45f8669ff7faba79f093.js:1)
    at _s (main.45f8669ff7faba79f093.js:1)
    at gs (main.45f8669ff7faba79f093.js:1)

I think the ac-layer throw this execption.
I use a custom component to embed the ac-layer. 
The template is:
<ac-layer acFor="let webcam of webCams$" [show]="show" [context]="this" [store]="true">
  <ac-label-desc props="{
                  position: webcam.position,
                 text: webcam.name
          }">
  </ac-label-desc>
</ac-layer>

It does not throw the exception when commenting the 'ac-label-desc' component.

**Version**
- angular-cesium@0.0.49
- cesium@1.46.1
- angular@6.0.8

**Comment by eitanfr** [comment]
Thx for letting us know, 
There is an issue with angular 6 and prod build. 
It's related to angular-parse and aot build, I guess we will be free to work on it next month. Of course you are welcome to open a PR for it.

**Comment by YeisonGomez** [comment]
Hi, what has happened to this?
I have the same problem

**Comment by joschne** [comment]
I have the same problem.

any idea what the problem might be?

**Comment by dovip** [comment]
i get same error with

angular-cesium@0.0.48
cesium@1.42.0
angular@5.2.10​

hope for help
