### ISSUE TITLE
/map-events-mananger/event-registration-input.d.ts(10,19): error TS7006: Parameter 'any' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by YeisonGomez** [TGFTech/angular-cesium#233]
Hi, i have generated a project in angular 6 with ngx-rocket and ng-cli, however, I get this error when executing it with npm start, something I can do about it?

Also, when I update a ts file the error appears but at the end "Compiled successfully".

Here is a detail of my console when I just use npm start and after updating a ts file:

![image](https://user-images.githubusercontent.com/14795272/43683490-83e72e6e-9852-11e8-901f-a2edb70493fd.png)

**Sorry for my English By: Google Translator**

**Version**

- angular-cesium@0.0.51
- cesium@1.48.0
- angular@6.0.1

**Comment by eitanfr** [comment]
try adding:
```
"noImplicitAny": false
```
to your tsconfig.json

**Comment by bampakoa** [comment]
@YeisonGomez `noImplicitAny` is an option of the Typescript compiler which when set to true it raises error on expressions and declarations with an implied any type.

**Comment by eitanfr** [comment]
seems all good here :)
closing the issue
