### ISSUE TITLE
<ac-circle> with error Cannot create property 'semiMejorAxis' on string '{position:track.position,radius:5000,granularity:0.08}' 

### ISSUE THREAD

**Issue by mrkimmy** [TGFTech/angular-cesium#235]
**Intended outcome:**
I want to add circle around plane 3D model so I use ac-circle

**Actual outcome:**
I got error below
![image](https://user-images.githubusercontent.com/14201370/44319527-9f3d1500-a466-11e8-91dc-e5ac8efc091f.png)

**How to reproduce the issue:**
I cloned project from git@github.com:TGFTech/angular-cesium.git and add code below for ac-circle in track-layer.component.html at line number 49.
![image](https://user-images.githubusercontent.com/14201370/44319637-4ae66500-a467-11e8-878c-57beeb048e9a.png)

I'm not sure did I do something wrong. Could you please help me about this error.

**Comment by eitanfr** [comment]
hi, tried to add `<ac-circle>` to `<track-layer>` and all worked, checkout the images below....
maybe you did another thing that caused the error? 

![image](https://user-images.githubusercontent.com/9163916/44397288-8d33a300-a548-11e8-88b3-4d028e307ee5.png)
![image](https://user-images.githubusercontent.com/9163916/44397340-b3594300-a548-11e8-9573-44cb0e4efbc7.png)

**Comment by eitanfr** [comment]
inside `ac-layer` you must use `<ac-XXX-desc>` components . check out [this](https://github.com/TGFTech/angular-cesium#ac-entity-desc-vs-ac-entity).
And for creating a sphere you can use `<ac-ellipsoid-desc>` ... good luck!

**Comment by mrkimmy** [comment]
Hi eitanfr

Oh I made mistake, I have to use `<ac-xxx-desc>` components in `<ac-layer>`. Thank you for your advice.

I tried to draw sphere using `<ac-ellipsoid-desc>`. I work sometime. Sometime when I reload web page the spheres did not appear. 

If I leave web page running for a while the sphere's position did not update along with track position like screenshot below

![image](https://user-images.githubusercontent.com/14201370/44503613-6d73ba80-a6c1-11e8-9513-26a7162dd0d2.png)

**Comment by EladIsraeli** [comment]
look at your props, you put an extra ','
your props be like that:

props="{
position: track.position,
radius: 40000.0,
granularity: 0.03
}"

instead of 

props="{
position: track.position,
radius: 40000.0,
granularity: 0.03,
}"

let me know if it fixed your problem. @mrkimmy

**Comment by mrkimmy** [comment]
> look at your props, you put an extra ','
> your props be like that:
> 
> props="{
> position: track.position,
> radius: 40000.0,
> granularity: 0.03
> }"
> 
> instead of
> 
> props="{
> position: track.position,
> radius: 40000.0,
> granularity: 0.03,
> }"
> 
> let me know if it fixed your problem. @mrkimmy

Hi EladIsraeli,

Sorry for lately reply.
Remove extra ',' not solve my problem.  
As eitanfr's answer I have to use `<ac-circle-desc>` inside `<ac-layer>` that solved my problem.

Thank you.
