### ISSUE TITLE
Setting "parent" property for AcEntity

### ISSUE THREAD

**Issue by hydrosquall** [TGFTech/angular-cesium#239]
[This Stackoverflow](https://stackoverflow.com/questions/36456110/how-to-create-a-multipolygon-in-cesium) answer from 2 years ago indicates MultiPolygons aren't supported in Native Cesium, but linked to a code sample for how to do this in vanilla cesium using the "parent" property.

https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Show%20or%20Hide%20Entities.html

I was wondering if anyone might know whether there's a sensible way to set the "parent" property using `AcEntity`. I tried porting the code sample below to `angular-cesium`, but the parent references didn't hold. I wasn't sure if I should be threading through AcNotification `id` or something similar rather than direct object references.

The use-case for this is that I want to make clicking on any one of the "child" entities with the same parent trigger the same handler, since I'm working with country data (many of which are represented as GeoJSON MultiPolygons.)  

Thanks for any guidance or tips you may have!

**Version**
- angular-cesium@<1.47.0>

**Comment by eitanfr** [comment]
hi there,
for the cesium example you added i would just use `ac-layer` as the parent container with the `show `attribute:
```html
<ac-layer acFor="let polygon of polygons$" [show]="show" [context]="this">
   <ac-polygon-desc props="{
                // polygon props
            }">
    </ac-point-desc>
</ac-layer>
```

so `ac-layer` is like a parent and you can perform actions on all the entities in the layer or a specific entity in the layer. hope it answers your needs.

**Comment by hydrosquall** [comment]
My challenge is that I want to have a top level set of polygons and multipolygons right next to each other - would it work if I nested a mixture of `ac-polygon-desc` and `ac-layer` as siblings of each other under the top-level `ac-layer`?

**Comment by eitanfr** [comment]
check out `<ac-array-desc>`
example:
https://github.com/TGFTech/angular-cesium/blob/master/demo/app/components/tracks-with-arrays-example/tracks-with-arrays.component.html

**Comment by hydrosquall** [comment]
@eitanfr I think this is just what I was looking for! Thank you :)
