### ISSUE TITLE
Docs: wrong documentation in ac-model-desc

### ISSUE THREAD

**Issue by hodbauer** [TGFTech/angular-cesium#243]
**Documentation issue:**
In `ac-model-desc` there is a wrong documentation.
In [this line](https://github.com/TGFTech/angular-cesium/blob/master/src/angular-cesium/components/ac-model-desc/ac-model-desc.component.ts#L13) it should reference to [`ModelGraphics`](https://cesiumjs.org/Cesium/Build/Documentation/ModelGraphics.html) instead of `PolygonGraphics`.
It also wrong in the [official documentation](https://tgftech.github.io/angular-cesium/components/AcModelDescComponent.html).

**Comment by eitanfr** [comment]
Thx for pointing it!
we will try to fix it soon, also PRs are welcomed :)

**Comment by tomermoshe** [comment]
Will be fixed in #245 PR
