### ISSUE TITLE
Layer acFor and Observable implementation seem logically wrong

### ISSUE THREAD

**Issue by bargoldi** [TGFTech/angular-cesium#37]
I've created some `ac-layer`.
In my component TS file, I need to create some observable.
It seems not intuitive to iterate over my data array and use `observer.next()` on each entity.
Because of the use of acFor - it seems like the FOR should loop over the observable array and I (the client) am not supposed to iterrate over my data inside of my component.

Example - taken from your demo:
```
this._socket.on('birds', (data) => {
    data.map((acNotification) => {
	 let action;
	 if (acNotification.action === 'ADD_OR_UPDATE') {
		 action = ActionType.ADD_UPDATE;
	 }
	 else if (acNotification.action === 'DELETE') {
		 action = ActionType.DELETE
	 }

	 acNotification.actionType = action;
	 acNotification.entity = convertToCesiumObj(acNotification.entity);
	 observer.next(acNotification);
    });
});
```

If I have the correct data I won't even need to iterate. It seems like the logically right way to use it would be:
```
// In case the data is right and I don't need to `map` anything
this._socket.on('birds', (data) => {
       observer.next(data);
});
```

Maybe there is something that I'm missing about the things going around behind the scenes, but the current usage seems just logically wrong.

**Comment by eitanfr** [comment]
acFor accepts Observer<AcNotifications>, a steam on AcNotifications objects, you can think of it as "updatable array". 
in our example, we send tracks as chunks - data contains an array of tracks, that way we need to map it from the array of tracks to AcNotiofcations observer updates. it up to the user to provide a valid Rx observer and it can be created from anything that the user wants (REST,static array, push updates with a single entity and etc).

about the acFor, it currently this way to keep it consist with angular ngFor syntax "ngFor=let item of observer | async", the observer is of type observer<item> not an array of items. in angular-cesium it's the same but without the async pipe. But we considering to change the AcFor prop name to DataSoure or something like that to make it more clear.
