### ISSUE TITLE
Dyanamically removing map layer provider

### ISSUE THREAD

**Issue by bargoldi** [TGFTech/angular-cesium#38]
Let's say I have an ac-map-layer-provider component representing some layer on the map.
I'm using ngIf to hide it.
I'm expecting the layer to remove from the Cesium viewer.

**Comment by eitanfr** [comment]
you shouldn't expect that, as all of the angular-cesium components only describe to cesium what to render aka the object that is rendered on the map aren't dom elements(for performance reasons), they are "descriptions" that tell cesium how to create elements using cesium api. 
for example, let say you have <ac-layer> for tracks if you use ngIf and remove the component all primitives that already were rendered won't be deleted.  
maybe we should make our doc more clear about that. 

maybe in the future, we can do something like "remove logic" for each component onDestoty  hook, need to think about the pros and cons of it.

**Comment by bargoldi** [comment]
> maybe in the future, we can do something like "remove logic" for each component onDestoty hook, need to think about the pros and cons of it.

That's exactly what we need.
As people integrate angular-cesium they prefer using Angular features rather than actually touching cesium objects/viewer/scene.

**Comment by tomermoshe** [comment]
#41 && #43 solved that issue. You can now use *ngIf with ac-layer, ac-map-provider and any kind desc component.
