### ISSUE TITLE
Cannot find module 'angular-cesium/angular-cesium.module'.

### ISSUE THREAD

**Issue by lybc** [TGFTech/angular-cesium#39]
```bash
npm install --save angular-cesium
```
![image](https://cloud.githubusercontent.com/assets/9601872/25841961/c32b6032-34d4-11e7-8123-e5d19fc69292.png)
The directory in the node_modules folder is like this：
![image](https://cloud.githubusercontent.com/assets/9601872/25842035/01506628-34d5-11e7-9605-088027c7fe31.png)

the angular-cesium.module is not a ts file.

How do i use it?

**Comment by eitanfr** [comment]
hi,
angular-cesium is bundled to umd file.
just do: `import { AngularCesiumModule } from 'angular-cesium';` like any other npm package...
Insead of `import { AngularCesiumModule } from 'angular-cesium/angular-cesium.module';`,
Also we updated the README file, check out the getting-started

**Comment by lybc** [comment]
Thank you for your update!
Now I can import AngularCesiumMoudle, but I am fully compliant with the entry file configuration project, still can not find many resource files.

I just create a `<ac-map>`, so many errors like this

![image](https://cloud.githubusercontent.com/assets/9601872/25881601/824a92a8-3570-11e7-8840-d89f69f7c9aa.png)

**Comment by eitanfr** [comment]
it seems that you dont serve cesium files properly.
do you use angular cli? try following [this](https://github.com/TGFTech/angular-cesium#cesium-configuration) steps

**Comment by lybc** [comment]
yes, but I used the angular 4. this is the fail reason?

this is my .angular-cli.json
```json

"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "ssc-display"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "assets": [
        {"glob": "**/*", "input": "../node_modules/cesium/Build/Cesuim", "output": "./asset/cesium"},
        "assets",
        "favicon.ico"
      ],
      "styles": [
        "styles.css",
        "../node_modules/cesium/Build/Cesium/Widgets/widgets.css"
      ],
      "scripts": [
        "../node_modules/cesium/Build/Cesium/Cesium.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
```

**Comment by eitanfr** [comment]
it looks like you have some typo in `"assets"` section:
change form `"../node_modules/cesium/Build/Cesuim"` to `"../node_modules/cesium/Build/Cesium"` and from `"./asset/cesium"` to `"./assets/cesium"`

**Comment by lybc** [comment]
oh god, It was a foolish mistake.

But after the correction or have the same problem
