### ISSUE TITLE
Can't run the Demo on Cesium V1.33.0 and V1.34.0

### ISSUE THREAD

**Issue by shiloDrot** [TGFTech/angular-cesium#59]
I tried to run the demo with a new version of Cesium, but it's not working.

The message on V1.33.0: 
Uncaught Error: Core/GoogleEarthEnterpriseMetadata missing ThirdParty/pako_inflate

The message on V1.34.0: 
Cesium missing ThirdParty/pako_inflate

**Comment by eitanfr** [comment]
seems an issue with cesium: 
[https://github.com/AnalyticalGraphicsInc/cesium/issues/5278](https://github.com/AnalyticalGraphicsInc/cesium/issues/5278)

**Comment by xujinghai** [comment]
When i try to use the cesium V1.35.2, I get same problem: "Uncaught Error: Cesium missing ThirdParty/pako_inflate" .

The interest thing is the error info came from the vendor.js. So i guess the problem may be from webpack.
here is the debug info in my webstorm.

![default](https://user-images.githubusercontent.com/24927529/28274660-1bc9cac6-6b44-11e7-968a-1db9626a3978.png)

**Comment by eitanfr** [comment]
tested it with cesium 1.35.2 and worked!
my dependecies:

<img width="516" alt="screen shot 2017-07-20 at 21 11 06" src="https://user-images.githubusercontent.com/9163916/28432292-124a8a6e-6d90-11e7-86c9-4f2f1f360640.png">

still having problems?

**Comment by xujinghai** [comment]
I suggest to close this issue. I found the demo  had problems. But when i directly use cesium-angular package in a new project. it has no problem.

**Comment by eitanfr** [comment]
resolved #70
