### ISSUE TITLE
How to load 3D titles models?

### ISSUE THREAD

**Issue by xujinghai** [TGFTech/angular-cesium#68]
Hi eitanfr, You did great jobs. Thanks.

I want to use this project to load photogrammetry models. Can the angular-cesium load 3D titles models? Please help to provide an example.

**Comment by eitanfr** [comment]
Thx, we are planning to add more features, better demo and improve the doc.
But currently, it not supported as an angular-cesium component.
On the meanwhile, you can create it using the regular cesium API.
we expose the cesium scene through the `CesiumService`:
```
import { CesiumService} from 'angular-cesium';

class MyMap {
 constructor(cesiumService: CesiumService) {
  const scene =  cesiumService.getScene();
  // create your 3d tiles using the scene 
 }
}
```
And ofcourse we welcome PRs :)

**Comment by xujinghai** [comment]
ok,thanks
