### ISSUE TITLE
Can not create application!

### ISSUE THREAD

**Issue by nickyxu** [TGFTech/angular-cesium#71]
Dear,
     I just follow the steps to create an application. But it doesn't work!

The error:
main.js:469 Uncaught ReferenceError: Cesium is not defined
    at main.js:469

which point to 
    EllipsePrimitive.borderStyleToPrimitiveType = {
        solid: Cesium.PrimitiveType.LINE_LOOP,
        dashed: Cesium.PrimitiveType.LINES
    };

I followed the guide.
npm install --save angular-cesium (which version is 0.11)
npm install --save cesium (which version is 1.35.1)

Import AngularCesiumModule in app.module.ts file.
Set cesium config in .angular-cli.json like this:
"assets": [
        "assets",
        "favicon.ico",
        {
          "glob": "**/*",
          "input": "../node_modules/cesium/Build/Cesium",
          "output": "./assets/cesium"
        }
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "../node_modules/cesium/Build/Cesium/Widgets/widgets.css",
        "styles.css"
      ],
      "scripts": [
        "../node_modules/cesium/Build/Cesium/Cesium.js"
      ],

And I do declare Cesium in typings.d.ts file.
/* SystemJS module definition */
declare var Cesium: any;
declare var module: NodeModule;
interface NodeModule {
  id: string;
}

My application is created by webstorm 2017.

Please help me!

**Comment by eitanfr** [comment]
Tested it with cesium 1.35.1 and worked perfectly, 
seems that Cesium wasn't loaded properly, but I can't tell why your CLI config looks ok.
does Cesium object exists on your global? (run `Cesium` in the console), does the cesium script in the .angular-cli.json point to the actual files?

**Comment by nickyxu** [comment]
Thanks eitanfr!

I doublechecked my configuration.
With the last angular-cli, the app(ng new project) is based on angular 4.
I think it is conficted with 0.11 angular-ceisum.
It works now!

Thanks again!
