### ISSUE TITLE
Offline option of map layer provider does not work.

### ISSUE THREAD

**Issue by gotenxds** [TGFTech/angular-cesium#72]
in this file 
[map-layer-provider.component.ts](https://github.com/TGFTech/angular-cesium/blob/17f5669b5e179fc2288777e91bcafeff288c4b0e/src/components/ac-map-layer-provider/ac-map-layer-provider.component.ts)

The switch case for :
`

		switch (this.provider) {
			case MapLayerProviderOptions.WebMapService:
				this.layerProvider = AcMapLayerProviderComponent.createWebMapServiceProvider(this.options);
				break;
			case MapLayerProviderOptions.WebMapTileService:
				this.layerProvider = AcMapLayerProviderComponent.createWebMapTileServiceProvider(this.options);
				break;
			case MapLayerProviderOptions.ArcGisMapServer:
				this.layerProvider = AcMapLayerProviderComponent.createArcGisMapServerProvider(this.options);
				break;
			case MapLayerProviderOptions.OFFLINE:
				break; <-- remove this
			default:
				this.layerProvider = AcMapLayerProviderComponent.createOfflineMapProvider();
				break;
		}
`

Has a redundant `break` it skips over and does nothing, remove it or remove the option completely so it goes to default.

**Comment by eitanfr** [comment]
👍 nice that you noticed.
already fixed in #70,
will merge it soon

**Comment by eitanfr** [comment]
resolved #70

**Comment by sameer1319** [comment]
Hi I have a quick question I am new to Cesium how would I use offline maps?
