### ISSUE TITLE
AcHtml explodes when cesium returns undefined.

### ISSUE THREAD

**Issue by gotenxds** [TGFTech/angular-cesium#74]
Hi again, (its David btw)
In AcHtml (which is not the docs for some reason.) we use cesium's `wgs84ToWindowCoordinates` to get the current position of the html component relative to the Cartesian position, this method has some issues that has been reported to cesium back in 2015 but has not yet been dealt with and wont be anytime soon, some times it returns  incorrect values, some times it returns undefined which makes this line:
[AcHtml-L33](https://github.com/TGFTech/angular-cesium/blob/master/src/components/ac-html/ac-html.component.ts#L33)
    `this.elementRef.nativeElement.style.top = `${screenPosition.y}px`;` explode, as scrrenPosition is undefined.

*note that this only happens when the acHtml component is offscreen, so you cant see it anyway.

This is a cesium issue, but it wont be solved anytime soon and we can solve this by simply adding a check
` if (screenPosition) {...}`.

Also, as a btw, we directly set the `ElementRef` style in this code, which is bad practice according to [angular](https://angular.io/api/core/ElementRef), we should instead use [renderer2](https://angular.io/api/core/Renderer2)
as in replace 
`this.elementRef.nativeElement.style.top = ${screenPosition.y}px`
with
` this.renderer.setStyle(this.elementRef, 'top', ${screenPosition.y}px);`

If you would like I can make this quick changes and make a pull request.

**Comment by tomermoshe** [comment]
If you can create PR for that it will be awesome
