### ISSUE TITLE
cesiumservice usage

### ISSUE THREAD

**Issue by dorperetz** [TGFTech/angular-cesium#77]
hello , youve got a great product !
my problem is 
there is no way to inject CesiumService and use the getViewer & getScene functions in a component/service which is located out side of ac-map in the dom hirarchy

**Comment by eitanfr** [comment]
thx!!
we will look into it

**Comment by eitanfr** [comment]
@dorperetz  check out version 0.0.13
it includes `ViewersManagerService` for getting cesium viewer out side of the hierarchy. according to #79
