### ISSUE TITLE
How to use EventManager?

### ISSUE THREAD

**Issue by nickyxu** [TGFTech/angular-cesium#86]
Dear all,
     I have a question. I noticed that we have an EventManager service(MapEventsManagerService).  However, the MapEventsManagerService should be used in child component of ac-map, just like ac-layer.

In my opinion, the MapEventsManagerService should be a logic for ac-map, not for ac-layer, is that right?
Could you mind supporting a public method to get the instance from ac-map, for example getMapEventsManager().
I think this is similar to getCesiumViewer method of ac-map components.

**Comment by eitanfr** [comment]
Generally, we recommend splitting all the layers, entities and their logic under `ac-map` to different components. This way you keep your code clearer and organized, so map events logic will be inside those components. 
But I agree if for some reason `mapEventManagerService` is needed it should be exposed. 
Check out #87  :)

**Comment by nickyxu** [comment]
OK! 
I agree with you. We need the both logic, for layer and for map.

Thanks a lot!
