### ISSUE TITLE
PICK_FIRST not working when any polyline has PolylineDash material

### ISSUE THREAD

**Issue by Nirco96** [TGFTech/angular-cesium#88]
Clicking an object on the map (or clicking multiple times) on an empty area while there is a polyline with Dash material throws an error  Cannot read property 'distanceSquaredTo' of undefined, causing any PICK_FIRST event to not work.
Tried with Cesium versions 1.33.0 and 1.31.0, also tried replicating the issue on a clean cesium project and it did not happen.

**Comment by eitanfr** [comment]
tried to run the following code and had no errors:
with `cesium 1.36` and `angular-cesium 0.0.14`
```html
<ac-layer acFor="let polyline of polylines$" [context]="this" [show]="show">
    <ac-dynamic-polyline-desc props = "{
        width : polyline.dynamicPolyline.width,
        positions: polyline.dynamicPolyline.positions,
        material: dash
    }">
    </ac-dynamic-polyline-desc>
</ac-layer>
```
in component.ts:
```javascript
ngOnInit() {
         dash = Cesium.Material.fromType('PolylineDash', {
		color : Cesium.Color.RED,
		gapColor : Cesium.Color.TRANSPARENT,
		dashLength : 12.0
	     };
	const input: EventRegistrationInput = {
		event: CesiumEvent.LEFT_CLICK,
		pick: PickOptions.PICK_FIRST,
			
	};
	this.eventManager.register(input).subscribe((result)=>{
		  console.log('result', result.entities);
	});
}
```

maybe try to upgrade your versions .

**Comment by eitanfr** [comment]
is it still relevant?
