### ISSUE TITLE
ac-circle on destroy causes app crash

### ISSUE THREAD

**Issue by dorperetz** [TGFTech/angular-cesium#92]
Hey guys,
when the ac-circle object ngOnDestroy function is called the app crashes.
does the ngOnDestroy has any difference treatment on ac-circle ?

**Comment by eitanfr** [comment]
strange , ac-circle doesnt have a unique OnDestory logic, 
which component do you use? `ac-circle-desc` or `ac-dynamic-circle-desc`

**Comment by eitanfr** [comment]
is it still relevant?
