### ISSUE TITLE
Failed to load MapEventsManagerService

### ISSUE THREAD

**Issue by nouhouari** [TGFTech/angular-cesium#99]
I've created a component and I want to handle the map mouse events.
I'm trying to import and use the MapEventManagerService but I got an error : 

> Error: No provider for CesiumService!

Here is my code

```
import { MapEventsManagerService } from 'angular-cesium/src/services/map-events-mananger/map-events-manager';


@Component({
  selector: 'app-raw',
  templateUrl: './raw.component.html',
  styleUrls: ['./raw.component.css'],
  providers: [
    MapEventsManagerService
  ]
})
export class RawComponent implements OnInit {

  constructor(private cesium: MapEventsManagerService) {
    // Register mouse handlers
    ...
  }

}
```
I can't found from the demo code where the CesiumService is provided.

**Comment by nickyxu** [comment]
I think this question is from angular, the ngmodule provider vs. the component provider.
Because you use privoder for mapeventservice in your componet, the angular create eventservice instance for you.
That is different from the eventservice instance from angular-cesium ac-map component.

The right usage for eventservice is: ac-map.getMapEventManager method.

Please double-check #86 and #87 .

Cheers,
Nicky Xu

**Comment by eitanfr** [comment]
@nickyxu is correct , 
add to the readme: 
`MapEventsManagerService` is porivided by `<ac-map/>`, therefor has 2 possibilitis to reach it:

1. In any components under `<ac-map/>` hierarchy as seen in the example (recomannded).
2. Using @viewChild and ac-map reference: `acMapComponent.getMapEventManagerService()` .

**Comment by nouhouari** [comment]
I manage to use the view with @ViewChild and bind it to <ac-map/> component but there is no such method getMapEventManagerService()

```
export declare class AcMapComponent implements OnChanges, OnInit {
    private _cesiumService;
    private _elemRef;
    private document;
    private viewersManager;
    private billboardDrawerService;
    private labelDrawerService;
    private ellipseDrawerService;
    private polylineDrawerService;
    private polygonDrawerService;
    private arcDrawerService;
    private pointDrawerService;
    private static readonly DEFAULT_MINIMUM_ZOOM;
    private static readonly DEFAULT_MAXIMUM_ZOOM;
    private static readonly DEFAULT_TILT_ENABLE;
    private static defaultIdCounter;
    disableDefaultPlonter: boolean;
    minimumZoom: number;
    maximumZoom: number;
    enableTilt: boolean;
    id: any;
    flyTo: any;
    private mapContainer;
    constructor(_cesiumService: CesiumService, _elemRef: ElementRef, document: any, viewersManager: ViewersManagerService, billboardDrawerService: BillboardDrawerService, labelDrawerService: LabelDrawerService, ellipseDrawerService: EllipseDrawerService, polylineDrawerService: PolylineDrawerService, polygonDrawerService: PolygonDrawerService, arcDrawerService: ArcDrawerService, pointDrawerService: PointDrawerService);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    getCesiumViewer(): any;
    getId(): any;
}
```

**Comment by dotansimha** [comment]
@nouhouari please update your `angular-cesium` version to the latest (0.0.18)

**Comment by nouhouari** [comment]
Definitely better with the right version.
